### PR TITLE
feat: Remove CASC Plugin and associated configuration as unused

### LINKED ISSUE #35: Use of the nexus-casc-plugin which ceased to work and is no longer actually used in this Project

### PR DESCRIPTION
**Pull request by madpah**
Resolves #35.

Few typos corrected also.

### CODE REVIEW

**Review by hboutemy — APPROVED** [review]
I suppose the impact is that Repository Firewall configuration has to be done by hand in Nexus Repo Pro/ = something that was done with this NXRM casc, as well as additional hosted+proxy configuration?

**Comment by madpah** [comment]
> I suppose the impact is that Repository Firewall configuration has to be done by hand in Nexus Repo Pro/ = something that was done with this NXRM casc, as well as additional hosted+proxy configuration?

So yes and no - the CasC plugin was there originally to perform an amount of this configuration in NXRM, however it hasn't worked for a long while - so we are no worse off for removing it at this point in time.

**Comment by hboutemy** [comment]
what surprises me in the current state is that NXRM comes with absolutely no proxy nor hosted configuration, nor blob store: is it me?

**Comment by madpah** [comment]
I just get a set of default Maven repositories when I start clean. That's all.

**Comment by hboutemy** [comment]
> I just get a set of default Maven repositories when I start clean. That's all.

I don't have even this basic default

**Comment by hboutemy** [comment]
immediate conclusion is: we can merge this PR
and debug in a separate issue the NXRM default Maven repositories missing when starting clean

**Comment by madpah** [comment]
Do you want to create a new Issue for the above @hboutemy ?

**Pull request merged**
