### PR TITLE
feat: use docker volumes & nxrm pro to use PostgreSQL

### LINKED ISSUE #37: FEAT: Use Docker Volumes, not Mount Volumes for Persistent Data
There are various permission challenges with using mount volumes, although they make a Developers life more transparent.

### PR DESCRIPTION
**Pull request by madpah**
This PR initially set out to resolve #37 - however in order to achieve this, #16 was also required to be included.

This is due to the nature of how the Sonatype Nexus Repository Container Images use the `/nexus-data` directory.

### CODE REVIEW

**Comment by hboutemy** [comment]
Tested on Linux, with a license copied to `config/sonatype-license-all.lic`:
- `proxied` profile works (just has warning on postgres-nxrm_1 `FATAL:  sorry, too many clients already`)
- `direct` profile is not ok, issue accessing the same license file through volume: 
```
ERROR: for sonatype-platform-reference_nxiq-direct_1  Cannot start service nxiq-direct: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/herve/tmp/sonatype-platform-reference/config/sonatype-license-all.lic" to rootfs at "/sonatype-license.lic": mount /home/herve/tmp/sonatype-platform-reference/config/sonatype-license-all.lic:/sonatype-license.lic (via /proc/self/fd/6), flags: 0x500
Starting sonatype-platform-reference_nxrm3-direct_1  ... error
```

**Comment by madpah** [comment]
Can you confirm whether volumes were cleanup up / removed (`docker volume prune --all`) between testing the different profiles @hboutemy ?

**Comment by hboutemy** [comment]
ok, after `docker volume prune --all`, `direct` works exactly as `proxied`

I need to test also on Mac...

**Comment by hboutemy** [comment]
on Mac, `direct` profile works but not `proxied`:
```
 ✔ Container sonatype-platform-reference-postgres-1                   Created                                                                                                                                                                                         0.0s
 ✔ Container sonatype-platform-reference-postgres-nxrm-1              Created                                                                                                                                                                                         0.0s
 ✔ Container sonatype-platform-reference-proxy-1                      Stopped                                                                                                                                                                                         0.0s
 ✔ Container 9a1a53017ec7_sonatype-platform-reference-nxiq-proxied-1  Removed                                                                                                                                                                                         0.0s
 ⠋ Container sonatype-platform-reference-nxiq-proxied-1               Recreate                                                                                                                                                                                        0.0s
 ⠋ Container sonatype-platform-reference-nxrm3-proxied-1              Recreate                                                                                                                                                                                        0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/hboutemy/dev/git/sonatype-nexus-community/sonatype-platform-reference/data/nexus-data
```

**Review by hboutemy — APPROVED** [review]
great to see Linux working as smoothly as Mac now :)

**Pull request merged**
